function csp(directives) {
  return directives.join("; ");
}

function directive(name, sources) {
  return `${name} ${sources.join(" ")}`;
}

export const PUBLIC_CONTENT_SECURITY_POLICY = csp([
  directive("default-src", ["'self'"]),
  directive("base-uri", ["'self'"]),
  directive("object-src", ["'none'"]),
  directive("frame-ancestors", ["'none'"]),
  directive("form-action", ["'self'"]),
  directive("script-src", [
    "'self'",
    "https://challenges.cloudflare.com",
    "https://static.cloudflareinsights.com",
    "https://cdn.jsdelivr.net",
  ]),
  directive("style-src", [
    "'self'",
    "'unsafe-inline'",
    "https://fonts.googleapis.com",
    "https://cdn.jsdelivr.net",
  ]),
  directive("font-src", [
    "'self'",
    "https://fonts.gstatic.com",
    "https://cdn.jsdelivr.net",
  ]),
  directive("img-src", ["'self'", "data:", "https:"]),
  directive("media-src", ["'self'"]),
  directive("frame-src", [
    "https://challenges.cloudflare.com",
    "https://emb.fouita.com",
  ]),
  directive("connect-src", ["'self'", "https://challenges.cloudflare.com"]),
]);

export const ADMIN_CONTENT_SECURITY_POLICY = csp([
  directive("default-src", ["'self'"]),
  directive("base-uri", ["'self'"]),
  directive("object-src", ["'none'"]),
  directive("frame-ancestors", ["'none'"]),
  directive("form-action", ["'self'"]),
  directive("script-src", ["'self'", "https://cdn.jsdelivr.net"]),
  directive("style-src", [
    "'self'",
    "'unsafe-inline'",
    "https://fonts.googleapis.com",
    "https://cdn.jsdelivr.net",
  ]),
  directive("font-src", [
    "'self'",
    "https://fonts.gstatic.com",
    "https://cdn.jsdelivr.net",
    "data:",
  ]),
  directive("img-src", ["'self'", "data:", "https:", "blob:"]),
  directive("connect-src", ["'self'"]),
  directive("frame-src", ["https://challenges.cloudflare.com"]),
]);

export const API_CONTENT_SECURITY_POLICY = csp([
  directive("default-src", ["'none'"]),
  directive("base-uri", ["'none'"]),
  directive("object-src", ["'none'"]),
  directive("frame-ancestors", ["'none'"]),
  directive("form-action", ["'none'"]),
]);

export const SVG_CONTENT_SECURITY_POLICY = csp([
  directive("default-src", ["'none'"]),
  directive("img-src", ["'self'", "data:"]),
  directive("style-src", ["'unsafe-inline'"]),
  "sandbox",
]);

export const SECURITY_HEADERS = Object.freeze({
  "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
  "X-Content-Type-Options": "nosniff",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "Permissions-Policy": "camera=(), microphone=(), geolocation=()",
  "X-Frame-Options": "DENY",
});

const ADMIN_NOINDEX_HEADERS = Object.freeze({
  "Cache-Control": "no-store",
  "X-Robots-Tag": "noindex, nofollow",
});

const NOT_FOUND_NOINDEX_HEADERS = Object.freeze({
  "X-Robots-Tag": "noindex, follow",
});

export const STATIC_HEADER_RULES = Object.freeze([
  {
    path: "/*",
    headers: SECURITY_HEADERS,
  },
  {
    path: "/admin",
    headers: ADMIN_NOINDEX_HEADERS,
  },
  {
    path: "/admin/*",
    headers: ADMIN_NOINDEX_HEADERS,
  },
  {
    path: "/404.html",
    headers: NOT_FOUND_NOINDEX_HEADERS,
  },
  {
    path: "/fr/404.html",
    headers: NOT_FOUND_NOINDEX_HEADERS,
  },
  {
    path: "/en/404.html",
    headers: NOT_FOUND_NOINDEX_HEADERS,
  },
  {
    path: "/assets/images/*.svg",
    unset: ["Content-Security-Policy"],
    headers: {
      "Content-Security-Policy": SVG_CONTENT_SECURITY_POLICY,
    },
  },
]);

export function renderHeadersFile() {
  const lines = [
    "# Generated by build.js from lib/security-headers.mjs.",
    "# Keep CSP directives in that module; Cloudflare _headers requires each emitted header value on one line.",
    "",
  ];

  for (const rule of STATIC_HEADER_RULES) {
    lines.push(rule.path);
    for (const header of rule.unset || []) {
      lines.push(`  ! ${header}`);
    }
    for (const [name, value] of Object.entries(rule.headers || {})) {
      lines.push(`  ${name}: ${value}`);
    }
    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}
